apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: pubsub-event-2
spec:
  topic: newsDetails
  routes:
       default: /api/email/sendone
  pubsubname: newsfetch
  scope:
    - newsfetchsummarizeservice
    - aggregatornotification

    #default: /aggregatornotification/dapr/subscribe/newsNotificationDetails